### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by pulkitsinghal** [stevemao/angular-PapaParse#1]
Thanks for the angular wrapper!

If you're up for brainstorming, I was wondering if you know papa parse well enough to let me know where a hook for progress-update would go? Then I might be able to submit a PR to add some neat functionality like showing a progress bar while the file is being parsed.

**Comment by stevemao** [comment]
I'm not 100% sure but I would probably check the `step` function. 
Also, questions are better to be asked on http://stackoverflow.com/ so you can get better answers there.

**Comment by pulkitsinghal** [comment]
@stevemao - Thanks, I like your suggestion about stackoverflow! In this case I want to pick your brain specifically. I tend to use gitter.im for discussions (not questions really) on my github repos as it ties into them directly.

Good point about `step` function. I also found that in the following discussions on progress bar:
https://github.com/mholt/PapaParse/issues/171
https://github.com/mholt/PapaParse/pull/125
https://gist.github.com/bluej100/a91e11fd6a081b9d6c69
But they all seem to be web-worker focused even, even though the `step` approach probably applies equally well to non-worker scenario.

**Comment by stevemao** [comment]
So does it solve your problem?
