### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by djgoulart** [stevemao/angular-PapaParse#2]
Hello!

Please add add some docummentation for usage.

Thanks

**Comment by stevemao** [comment]
What kind of documentation are you looking for? This is just a wrapper for angular DI and all the docs should be available at https://github.com/mholt/PapaParse

**Comment by batjko** [comment]
Hi there,

I'm a little new to all of this, so have no idea how to start including this in my Angular app. What do I download, where do I put it, how do I make sure Papa's methods are available to me etc...

Thanks.

**Comment by stevemao** [comment]
You should probably read the angular docs and PapaParse docs. As I said this is just a wrapper for angular DI. If I write docs here it's gonna be exactly the same as angular and PapaParse so why write it twice?
